### ISSUE TITLE
SyntaxError: Invalid regular expression: Range out of order in character class

### ISSUE THREAD

**Issue by milesj** [devongovett/regexgen#19]
I'm receiving this error when trying run `match` on a regex pattern built with this library. The regex pattern is generated using emoji text and emoji presentation unicode characters.

Here is the regex pattern: https://raw.githubusercontent.com/milesj/emojibase/v1/packages/emojibase-regex/unicode/index.js (using `u` flag)

And here is the file that generates the regex: https://github.com/milesj/emojibase/blob/v1/src/generators/generateRegex.js

**Comment by devongovett** [comment]
hmm, looks like maybe it's missing the `u` flag

**Comment by milesj** [comment]
Derp, that was it. Missed that while refactoring. Thanks !
