### ISSUE TITLE
[question] revert the process

### ISSUE THREAD

**Issue by Kikobeats** [devongovett/regexgen#9]
Do you think that could be more or less easy to exactly the invert operation?

For example, return an array of all variations:

```
r[ae]d → ['red', 'rad']
```

**Comment by devongovett** [comment]
Definitely possible. I did something similar for [fontkit](https://github.com/devongovett/fontkit). Here's the algorithm you could implement:

1. Parse the regex into an AST.
2. Convert the regex into a DFA. Something like [this](https://github.com/devongovett/dfa/blob/master/src/dfa.js).
3. Treat the DFA as a graph, and do a depth first search. Upon finding an accepting state, add it to the result set.
